### ISSUE TITLE
Don't resolve hosts to IPv6 on machines that can't connect to IPv6 addresses

### ISSUE THREAD

**Issue by ivan** [chfoo/wpull#154]
DNS resolvers usually return IPv6 addresses even to machines that can't connect to said addresses.  Maybe wpull could use an IPv6 connectivity test on startup?  (e.g. grab google.com's IPv6 address, see if it can be reached.)

**Comment by chfoo** [comment]
Tasks
=====

* [ ] `dns.Resolver` to return a pair of results (address in IPv4 & IPv6)
* [ ] Check out on `connection.ConnectionPool` returns a pair of `Connection` instances or a wrapper around a pair of `Conenction` instances
* [ ] On connection, check in properly recycles the appropriate connection back
* [ ] Maintain a table of preferred addresses
