### ISSUE TITLE
Suggestion for adding youtube-dl metadata to warcs

### ISSUE THREAD

**Issue by ikreymer** [chfoo/wpull#252]
I wanted to suggest that perhaps we can coordinate how to add youtube-dl json metadata to WARCs. In webrecorder/pywb-webrecorder, I've implemented this by adding a metadata record as follows.
I'm not sure if wpull supports this yet (looks like its planned?) but it would be great if we could do this in a consistent way.

My approach has been as follows:
For a given url, the contents of `youtube-dl -j http://www.youtube.com/watch?v=aT-Up5Y4uRI` are stored in a WARC metadata record like this:

```
WARC/1.0
WARC-Type: metadata
WARC-Record-ID: <urn:uuid:784cf5d0-2438-4722-a9c6-0a7132e52503>
WARC-Date: 2015-01-10T07:23:20Z
WARC-Target-URI: metadata://www.youtube.com/watch?v=aT-Up5Y4uRI
WARC-Block-Digest: sha1:3DCPNT4UHEHH76ZMHIA527KEX6SMVDRU
Content-Type: application/vnd.youtube-dl_formats+json
Content-Length: 3650

<json metadata returned from youtube-dl>
```

The scheme `metadata://` is used to distinguish from actual captures and make it easier to filter in an index (cdx). The content-type of `application/vnd.youtube-dl_formats+json` was also something I picked.

pywb already supports this format, and it allow for complex replay situations (eg. multiple videos per page, such as: http://webenact.rhizome.org/vvork/20141006184408/http://www.vvork.com/?m=201205)

More details about the replay side of things:
https://github.com/ikreymer/pywb/wiki/Video-Replay-and-Recording

Also let me know if you think there's a better way to do it, I think we should standardize on an approach to make replay easier down the road.

**Comment by chfoo** [comment]
No, wpull doesn't save any metadata right now. It only captures the traffic but I would like to include them (#22). I haven't thought much about it but I think your specifications seem reasonable. I would follow your spec once I implement it Wpull.

Do you have something that documents any extra WARC specs you are using? For example, I have http://wpull.readthedocs.org/en/latest/warc.html which describes things that Wpull does that is not in the standard.

**Comment by ikreymer** [comment]
Sounds good. Thus far, this has been the only custom spec that I've been using, but creating such a document seems like a very good idea for future reference/compatibility.

**Comment by ikreymer** [comment]
I wonder if I should have used a `urn:` prefix instead of `metadata://`, ah well..

The IIPC general assembly meeting will have a discussion of the WARC standard, I wonder if it would make sense to somehow bring up these use cases?

For example, I've also been thinking of what the proper way to save a DOM snapshot should be.. Was considering either `resource` / `conversion` or  `metadata` ,   I see you've chosen `resource` which is what I was leaning towards as well..

**Comment by chfoo** [comment]
Whichever URI and Content-Type works is fine with me. If `metadata://` is already being used, my opinion would be to keep it unless there is issues with it.

I guess it won't hurt to ask. It seems like the standard implies that implementators are free to extend using their best judgement. For example like DOM snapshots, I chose `resource` because it doesn't explain how to fetch data (`metadata`) and `conversion` seems to imply feeding a file into deterministic program that produces another file in a different format.
