### ISSUE TITLE
--output-document leaves an empty file behind

### ISSUE THREAD

**Issue by bzc6p** [chfoo/wpull#275]
Debian 8.0, python 3.4, wpull 1.2.1.

Using the -O (or --output-document) option seems to fetch the file(s) properly, but the destination file, although created, is empty. Either if one URL or a list of URLs is given.

May be a regression, as I see this option was implemented long ago (in #42).

**Comment by ivan** [comment]
:+1:  spent an hour implementing some stuff with -O only to find that it didn't work :-)
