### ISSUE TITLE
successful download of unlikely URL

### ISSUE THREAD

**Issue by ethus3h** [chfoo/wpull#314]
This log entry looks like it should be an error, since the subdomain seems kind of funny looking and it won't open in my Firefox... correct me if I'm wrong though.

```
203 Non-Authoritative Information http://{,history.thefreemusic.ga/.ftpquota
```
I'm not sure what actually is being downloaded here.
Is this intended behavior? Thanks :)

**Comment by ethus3h** [comment]
I'm using grab-site with wpull 1.2.3.

**Comment by ivan** [comment]
It does have a DNS record for that domain:

```
# dig -t A '{,history.thefreemusic.ga'

; <<>> DiG 9.9.5-11ubuntu1.2-Ubuntu <<>> -t A {,history.thefreemusic.ga
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26614
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;{,history.thefreemusic.ga.	IN	A

;; ANSWER SECTION:
{,history.thefreemusic.ga. 299	IN	CNAME	thefreemusic.ga.
thefreemusic.ga.	299	IN	A	195.20.53.64

;; Query time: 196 msec
;; SERVER: 8.8.4.4#53(8.8.4.4)
;; WHEN: Fri Mar 04 03:08:36 UTC 2016
;; MSG SIZE  rcvd: 84
```

but I don't think any browser would be able to make a request to such a domain.

**Comment by ethus3h** [comment]
Ahh, huh, interesting, thanks! I didn't know those were valid characters for a domain name. Sorry for the bother!
