### ISSUE TITLE
wpull (grab-site) gets NetworkError on URL that wget and Firefox can download; reproducible on 2 different IPs

### ISSUE THREAD

**Issue by ethus3h** [chfoo/wpull#316]
So with this (kinda long) URL, grab-site (and vanilla wpull, too) give a NetworkError, but Firefox and wget both correctly give an HTML page: 

```
Resolving waybackr.com (waybackr.com)... 146.148.26.18
Connecting to waybackr.com (waybackr.com)|146.148.26.18|:80... connected.
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
Length: unspecified
Saving to: ‘apple-touch-icon-72x72.png’

apple-touch-icon-72     [ <=>                  ]     201  --.-KB/s   in 0s     

2016-03-09 20:24:36 (16.3 MB/s) - ‘apple-touch-icon-72x72.png’ saved [201]

grabbot@sd-86348:~/grabs$ cat ./apple-touch-icon-72x72.png 
<html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
grabbot@sd-86348:~/grabs$ 
```

versus
```
favicons/apple-touch-icon-72x72.png’ encountered an error:
 Connection closed.
ERROR Fetching ‘http://waybackr.com/scripts/*/favicons/favicons/favicons/favicon
s/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favico
ns/favicons/favicons/favicons/favicons/favicons/f
```

URL: `http://waybackr.com/scripts/*/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/favicons/apple-touch-icon-72x72.png`

**Comment by ethus3h** [comment]
wpull version: 1.2.3
grab-site version: 0.11
```
grabbot@sd-86348:~/grabs$ uname -api
Linux sd-86348 3.19.0-33-generic #38-Ubuntu SMP Fri Nov 6 18:18:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux_
grabbot@sd-86348:~/grabs$
```

**Comment by ivan** [comment]
Which URL does wget and Firefox succeed on?  The very long URL you pasted gets `414 Request-URI Too Large` anywhere.

**Comment by ivan** [comment]
Oh, I see what you mean

**Comment by ivan** [comment]
Note the

```
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
```

https://github.com/chfoo/wpull/issues/291

**Comment by ethus3h** [comment]
@ivan: That's an "error parsing status line", though, rather than a "connection closed"...

**Comment by chfoo** [comment]
HTTP 0.9 isn't supported yet which explains error parsing the status line that doesn't exist in HTTP 0.9

**Comment by ethus3h** [comment]
Oh, huh, ok. I guess the connection closed wasn't the issue in #291 then… I'll close this then, since it's I guess the same problem. Thanks! :)
