### ISSUE TITLE
File in cdx and log, but not in WARC when --concurrent set higher than 1

### ISSUE THREAD

**Issue by Svekla** [chfoo/wpull#319]
When I'm dumping any site using VPS SSD 1 from OVH with concurrent higher than 1, some files appear in cdx and log file, but not in WARC. For example in attached test dump, file: http://forum.postalsite.info/templates/PostalSite/images/folder_locked_big.gif is in .cdx:
```
http://forum.postalsite.info/templates/PostalSite/images/folder_locked_big.gif 1459376733 - - WQ26USAMZQQ4PC64GS7D2R7577WWSFC7 1092 219055 forumpostalsiteinfo-30032016-00000.warc.gz <urn:uuid:f66de344-8f69-4174-af54-89b603c4f5ac>
```
And log:
```
2016-03-31 00:25:32,851 - wpull.processor.web - INFO - Fetching ‘http://forum.postalsite.info/templates/PostalSite/images/folder_locked_big.gif’.
(...)
2016-03-31 00:25:33,280 - wpull.processor.web - INFO - Fetched ‘http://forum.postalsite.info/templates/PostalSite/images/folder_locked_big.gif’: 200 OK. Length: 455 [image/gif].
```
but not in WARC: (at least when opened in pywb and webarchiveplayer on Windows 8.1)
```
Url Not Found

The url http://forum.postalsite.info/templates/PostalSite/images/folder_locked_big.gif could not be found in this collection.
```

wpull version: 1.2.3
Python3 version: Python 3.4.3+
System: Ubuntu 15.10
Command:
```
wpull forum.postalsite.info -U 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36' -o wpull.log --database wpull.db --html-parser libxml2-lxml --save-cookies ciastko --no-check-certificate --delete-after --no-robots --page-requisites --no-parent --sitemaps --inet4-only --timeout 42 --tries 6 --waitretry 9 --warc-file forumpostalsiteinfo-30032016 --warc-cdx --warc-max-size 1073741824 --warc-move donewarc --debug-manhole --strip-session-id --escaped-fragment --session-timeout 63200 --max-redirect 16 --recursive --level inf --span-hosts-allow page-requisites --reject-regex "\?p=|&p=|\?cp=|&cp=|mark=forums|mark_topic=unread|mark=topics|watch=topic|ignore_topics\.php|pozdrowienia\.php|mode=post_beer|report.php|buddy=|mode=reply|mode=post|mode=email|mode=quote|mode=newtopic|privmsg\.php|profile\.php\?mode=viewprofile&u=(.*)&p=|cookie\.js|search\.php|safe\.php|logout=true|view=" --concurrent 10 --monitor-disk 500m
```
Maybe it's something on my end (when I'm running wpull my load average is around 0.70)? Thanks for help and sorry for my bad English.

Mentioned test dump:
[forumpostalsiteinfo-30032016.zip](https://github.com/chfoo/wpull/files/196727/forumpostalsiteinfo-30032016.zip)

**Comment by ivan** [comment]
You can verify that the WARC does indeed contain the response for `folder_locked_big.gif`: the .cdx file says there is a gz-compressed response record of 1092 bytes at position 219055, and you can confirm that the record is there:

```
# python -c 'f = open("forumpostalsiteinfo-30032016-00000.warc.gz"); f.seek(219055); print f.read(1092)' | gunzip
WARC/1.0
WARC-Type: response
Content-Type: application/http;msgtype=response
WARC-Date: 2016-03-30T22:25:33Z
WARC-Record-ID: <urn:uuid:f66de344-8f69-4174-af54-89b603c4f5ac>
WARC-Target-URI: http://forum.postalsite.info/templates/PostalSite/images/folder_locked_big.gif
WARC-IP-Address: 85.128.226.175
WARC-Concurrent-To: <urn:uuid:81c72d5e-27ef-43cf-be61-674afc7c66c7>
WARC-Block-Digest: sha1:N4OMUJLKPU7UHZTY2DBE6O7LRU5OFHJ7
WARC-Payload-Digest: sha1:WQ26USAMZQQ4PC64GS7D2R7577WWSFC7
Content-Length: 694
WARC-Warcinfo-ID: <urn:uuid:a01265ae-f1f6-49bf-b498-092f6079b56c>

HTTP/1.1 200 OK
Date: Wed, 30 Mar 2016 22:25:33 GMT
Content-Type: image/gif
Content-Length: 455
Connection: keep-alive
Last-Modified: Tue, 07 Oct 2014 09:43:01 GMT
ETag: "1c7-504d2066d04cc"
Accept-Ranges: bytes
Server: Apache/2

GIF89a((�������|rh]SI?4* 
�O2$�p��`:%,v9�6a ��gDA- ���!�,((��$�di�h��l��p,�t
�                       ?�Y0����)ZG�ܩ�b���ab8f~8f�xoe�eJ�E�T�Y^�3:T
�29uqZS�>8
}в8����    q�69�e���78	k��1��K6L8
        qVߙ8|����9Rl
                    ��Ȣ�YR`�T~�{@�&��t�+�'!�@԰i�.�,X
�2u\    �'                                                 ���aA,F`�堂R��DI���
�J*�Y�勦J_s�h4F%�~�
y��Iz�p�E!5�M�Y�ZE�_���";


gzip: stdin: unexpected end of file
```

So, either the problem is a lot more subtle or there is a bug in pywb and webarchiveplayer.

**Comment by ivan** [comment]
If this happens only with "concurrent higher than 1", pywb and webarchiveplayer might be expecting the response record to always follow the request record in the WARC.  wpull's WARCs don't seem to enforce a strict request/response pair ordering.

**Comment by Svekla** [comment]
I had this problem with --concurrent 2. I'm at ~2,5GB in other dump with --concurrent 1 and it seems, that everything works fine (it works in webarchiveplayer). Is there any better WARC viewer for Windows, that would work with wpull's WARCs? Thanks for help.

**Comment by ivan** [comment]
https://github.com/ukwa/webarchive-explorer is another WARC viewer ([I found it here](https://github.com/iipc/openwayback/wiki)), but I have not tried it.

In any case, probably worth filing a bug on pywb as well.

**Comment by ikreymer** [comment]
hi, just wanted to add a link to the filed issue here, ikreymer/pywb#175
I think I found the cause, related to the index generation -- it was caused when WARC records do not alternate `request` and `response` in the WARC file, which I assume a higher concurency is causing. Will issue a quick update release.
