### ISSUE TITLE
API For use as a urllib replacement in existing spider codebases

### ISSUE THREAD

**Issue by fake-name** [chfoo/wpull#324]
Hi there!

I have a fairly extensive existing scraper that's part of my own personal archiving system for a lot of online web fiction content. I've been thinking about if it were possible to possibly add the ability to log to warc files, for contributing to the internet archive project.

Basically, I have all my own thread management, page processing, spider system, database backend and all the associated plumbing.

What I'd love is the ability to basically specify a per-thread warc file, and have scraped content mirrored into the ward for periodic upload. I'd be happy to pitch in and help implement something like this, but I'm not sure if the internal architecture is amenable to what I described. 

Let me know if you think this is feasable & you're interested.

**Comment by ivan** [comment]
One alternative to doing this in wpull is to run https://github.com/internetarchive/warcprox and tell urllib to use the proxy.

**Comment by fake-name** [comment]
I considered that, but the issue then becomes the interaction between urllib, phantomjs (which I use internally) and the proxy.

Could I control the user-agent/cookiejar of the proxy some way on a per-request basis? I currently have a unique user-agent and cookiejar per-thread, which is moved into and out of phantomjs when something like cloudflare is detected. I'd need to be able to maintain that functionality though the proxy.

**Comment by ivan** [comment]
HTTP proxies (including warcprox) don't set a user-agent or manage a cookie jar, they just pass through the client's `User-Agent` and `Cookie` request headers.

**Comment by fake-name** [comment]
Yeah, reading it's source now. Hmm, that's a distinct possiblity.

**Comment by chfoo** [comment]
The code right now is a bit too tightly coupled since it wasn't the intention for it to have a public API. I'm the progress of rewriting things but it might be a while before things become usable. Also, I'm not sure if it would be suitable since it doesn't support threads.

I guess if you don't want to use a proxy, you can probably write your own WARC file writer provided that you have access to the raw bytes.

**Comment by fake-name** [comment]
That was kind of the impression I got. I'll look into appropriating some components from one of the WARC proxies. Thanks!
