### ISSUE TITLE
Quits unexpectedly. Was: Wpull Stops working (can't figure out problem).

### ISSUE THREAD

**Issue by luckcolors** [chfoo/wpull#326]
Linux Debian Jessie Armv71.
Python3.4 (installed python27, python3.5)
Commandline: check NewsGrabber
Here are the logs:
[Logs.zip](https://github.com/chfoo/wpull/files/298132/Logs.zip)
If you need extra info let me know.

**Comment by chfoo** [comment]
I'm not sure what "stops working" means. Did it freeze or quit unexpectedly?

**Comment by luckcolors** [comment]
Can't say what i only have are the logs.
