### ISSUE TITLE
Some page requisites not being saved when using --recursive

### ISSUE THREAD

**Issue by rory** [chfoo/wpull#386]
I am trying to archive a twitter mobile page, including all page requisites. When I don't do a recursive crawl, everthing works, and all page requisites are downloaded. When I do `--recursive --level 1`, many page requisites from the 'first' page aren't saved.

Regular non-recursive download: (In reality I save to a warc file, and get the same result)

    $ ../ve/bin/wpull -o wpull.log -q --page-requisites --span-hosts-allow page-requisites --delete-after https://mobile.twitter.com/hashtag/8thref
    $ grep /images/sprites/tweet_rt.gif ./wpull.log 
    2018-05-05 12:13:22,722 - wpull.processor.web - INFO - Fetching ‘https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/sprites/tweet_rt.gif’.
    2018-05-05 12:13:22,752 - wpull.processor.web - INFO - Fetched ‘https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/sprites/tweet_rt.gif’: 200 OK. Length: 98 [image/gif].

When I use `--recursive --level 1` (so that individual tweet pages are saved):

    $ ../ve/bin/wpull -o wpull.log --recursive --level 1 -q --page-requisites --span-hosts-allow page-requisites --delete-after https://mobile.twitter.com/hashtag/8thref
    $ grep /images/sprites/tweet_rt.gif ./wpull.log 

Nothing, that image isn't downloaded. Some of the images are downloaded and some are not.

wpull was installed with pip3, and is version 1.2.3. Python is 3.4.3. This is running on Ubuntu Linux 14.04.5, fully apt-get update'd

The URL (that isn't downloaded) is just a `src` in an `<img...>` tag. No complicated JavaScript stuff. (I'm not using `--phantomjs` in this crawl)

    $ ../ve/bin/wpull -o wpull.log -q --page-requisites --span-hosts-allow page-requisites https://mobile.twitter.com/hashtag/8thref
    $ grep -R /images/sprites/tweet_rt.gif ./mobile.twitter.com/
    ./mobile.twitter.com/hashtag/8thref:                    <img alt="Retweet"   src="https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/sprites/tweet_rt.gif"
    [repeated ~20 times]

I get the same results with (e.g.) `--page-requisites-level 5` (But I'm not sure what that option does)

**Comment by chfoo** [comment]
I looked into it using the `--debug` option. 
```
2018-05-05 11:39:05,071 - wpull.processor.web - DEBUG - Robots filter verdict False reason robotstxt
2018-05-05 11:39:05,071 - wpull.pipeline.session - DEBUG - Skipping ‘https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/sprites/verified.gif’.
```
When `--recursive` is used, it checks for `robots.txt` which is behavior copied from Wget. Can you try the `--no-robots` option?
