### ISSUE TITLE
Add feature to grab linked-to resources on other domains

### ISSUE THREAD

**Issue by ivan** [chfoo/wpull#66]
I almost always want to grab not just everything on domain.com, but also everything that it links to.  That is, I want to grab everything the `a href=""`s point to as if they were page requisites, even if they're on another domain.  Especially when domain.com has download links or important citations.  `--span-hosts -r` doesn't work for this because it starts spidering other domains with the same infinite depth.

The option for this feature could be named `--linked-pages`.  `--linked-page-requisites` could control whether the page requisites for those linked-to pages are grabbed as well.  I don't really care about the option name; I mention it for illustration.

I've used HTTrack hundreds of times just for this feature, and it's saved tons of stuff that wget would have missed without me noticing.

**Comment by chfoo** [comment]
Closing this issue since looks like this has been working well so far.
